
services: 
  
  backend:
    build: ./backend
    ports: 
      - "8086:8086"
    networks:
      - app-network 
    depends_on:
      - db  

  serverpx:
    build: ./server
    ports:
      - "8082:8082"
    networks:
      - app-network 
    depends_on:
      - db   
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - mydata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password   
      POSTGRES_DB: dbs
    networks:
      - app-network  


networks:
  app-network:
    driver: bridge

volumes:
 mydata: