name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0
  

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  postgres: ^3.4.4
  schema_dart: ^0.0.5

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.25.7

assets:
  - bin/sqlfileup.sql

